#!/usr/bin/env bash
# 動画の実演用サンプルプロジェクトを /tmp/harness-demo に作り直す。
#   bash demo/setup.sh            作る（毎回削除して作り直す）
#   bash demo/setup.sh dirty      作ったうえで「src を編集したがテスト未実行」の marker を置く
# 触るのは /tmp/harness-demo と $TMPDIR/claude-hooks-demo-<uid>/ だけ。実ホーム・実リポジトリ・~/.claude には触れない。
# 必要なもの: bash、jq、git。（tape を撮るなら vhs と tree）
set -euo pipefail
D=/tmp/harness-demo
rm -rf "$D" "${TMPDIR:-/tmp}/claude-hooks-demo-$(id -u)"
mkdir -p "$D"/{src,test,dist,docs,dev/tasks,scripts,.claude/{hooks,skills/quality-gate,skills/plan-task,rules,agents,workflows}}
cd "$D"
git init -q -b main

cat > package.json <<'EOF'
{
  "name": "harness-demo",
  "private": true,
  "scripts": { "test": "node --test", "build": "node scripts/build.js" }
}
EOF
cat > src/app.js <<'EOF'
export function greet(name) {
  return `hello, ${name}`;
}
EOF
cat > test/app.test.js <<'EOF'
import { test } from "node:test";
import assert from "node:assert/strict";
import { greet } from "../src/app.js";
test("greet", () => assert.equal(greet("world"), "hello, world"));
EOF
echo '// generated by scripts/build.js — do not edit' > dist/app.js
echo 'console.log("build")' > scripts/build.js

# ---- 真実源（設計文書）と CLAUDE.md（40 行以内） ----
cat > docs/design.md <<'EOF'
# 設計文書（真実源）

## 作業の原則
- main に直接 commit / push しない。作業は feature ブランチ + PR。
- dist/ は生成物。手で編集せず scripts/build.js で再生成する。
- src/ を編集したら `npm test` を通してから応答を結ぶ。
- 秘密情報（トークン、鍵）をリポジトリに書かない。
- 設計書に無い機能を「良かれと思って」足さない。必要なら止まって聞く。

## やらないこと
- テストの削除や skip で通す。
- 生成物 dist/ を手で直す。
EOF
cat > CLAUDE.md <<'EOF'
# harness-demo

ルールの本文は docs/design.md（真実源）。ここには毎回必要な事実だけを書く。

## コマンド
- テスト: `npm test`
- ビルド: `npm run build`（dist/ を再生成。dist/ は手で編集しない）

## 作業の原則（要点。詳細は docs/design.md）
- 作業は feature ブランチで行い、main に直接 commit しない。
- src/ を編集したら `npm test` を通す。
- 作業を始めるときは /plan-task、区切りでは /quality-gate。
EOF

# ---- hooks ----
cat > .claude/settings.json <<'EOF'
{
  "permissions": {
    "allow": ["Bash(npm test)", "Bash(npm run build)"],
    "deny": ["Bash(git push --force *)", "Read(./.env)"]
  },
  "hooks": {
    "SessionStart": [{ "hooks": [{ "type": "command", "command": "\"$CLAUDE_PROJECT_DIR\"/.claude/hooks/session-start.sh" }] }],
    "PreToolUse": [
      { "matcher": "Bash",            "hooks": [{ "type": "command", "command": "\"$CLAUDE_PROJECT_DIR\"/.claude/hooks/bash-guard.sh" }] },
      { "matcher": "Edit|Write",      "hooks": [{ "type": "command", "command": "\"$CLAUDE_PROJECT_DIR\"/.claude/hooks/file-guard.sh" }] }
    ],
    "PostToolUse": [
      { "matcher": "Edit|Write",      "hooks": [{ "type": "command", "command": "\"$CLAUDE_PROJECT_DIR\"/.claude/hooks/track-edit.sh" }] },
      { "matcher": "Bash",            "hooks": [{ "type": "command", "command": "\"$CLAUDE_PROJECT_DIR\"/.claude/hooks/track-test-run.sh" }] }
    ],
    "Stop": [{ "hooks": [{ "type": "command", "command": "\"$CLAUDE_PROJECT_DIR\"/.claude/hooks/stop-test-reminder.sh" }] }]
  }
}
EOF
cat > .claude/hooks/_lib.sh <<'EOF'
# 共通: marker の置き場（セッション単位、best effort）
marker_dir() { echo "${TMPDIR:-/tmp}/claude-hooks-demo-$(id -u)"; }
session_of() { jq -r '.session_id // "unknown"' <<<"$1"; }
EOF
cat > .claude/hooks/bash-guard.sh <<'EOF'
#!/usr/bin/env bash
# PreToolUse (Bash): 機械的に白黒がつく禁止事項だけを止める。拒否は exit 2 + stderr で
# 「なぜ」「正しい代替手順」「出典」を返す。
set -euo pipefail
input=$(cat)
cmd=$(jq -r '.tool_input.command // ""' <<<"$input")
branch=$(git -C "${CLAUDE_PROJECT_DIR:-.}" branch --show-current 2>/dev/null || echo "")

if [[ "$cmd" =~ git[[:space:]]+(commit|push) ]] && [[ "$branch" == "main" ]]; then
  echo "拒否: main ブランチ上での git commit / push は禁止です（docs/design.md「作業の原則」）。" >&2
  echo "代替: /plan-task で feature ブランチを切ってから commit してください。" >&2
  exit 2
fi
if [[ "$cmd" =~ (sed[[:space:]]+-i|>|tee)[^|]*dist/ ]]; then
  echo "拒否: dist/ は生成物です。手で書き換えず npm run build で再生成してください（docs/design.md）。" >&2
  exit 2
fi
exit 0
EOF
cat > .claude/hooks/file-guard.sh <<'EOF'
#!/usr/bin/env bash
# PreToolUse (Edit|Write): 生成物への書き込みと、秘密らしき文字列の混入を止める。
set -euo pipefail
input=$(cat)
path=$(jq -r '.tool_input.file_path // ""' <<<"$input")
content=$(jq -r '.tool_input.content // .tool_input.new_string // ""' <<<"$input")

case "$path" in
  */dist/*|dist/*)
    echo "拒否: $path は生成物です。scripts/build.js を直して npm run build で再生成してください（docs/design.md）。" >&2
    exit 2 ;;
esac
# 検出パターン（実トークンではない）。必要に応じて自分の環境の形式を足す
if grep -Eq '(ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----)' <<<"$content"; then
  echo "拒否: 書き込み内容にトークンか秘密鍵らしき文字列があります。環境変数か secret manager に置いてください（docs/design.md）。" >&2
  exit 2
fi
exit 0
EOF
cat > .claude/hooks/track-edit.sh <<'EOF'
#!/usr/bin/env bash
# PostToolUse (Edit|Write): src/ を編集したら dirty marker を置く（内部状態）
set -euo pipefail
. "$(dirname "$0")/_lib.sh"
input=$(cat)
path=$(jq -r '.tool_input.file_path // ""' <<<"$input")
case "$path" in
  */src/*|src/*) mkdir -p "$(marker_dir)"; touch "$(marker_dir)/$(session_of "$input").src-dirty" ;;
esac
exit 0
EOF
cat > .claude/hooks/track-test-run.sh <<'EOF'
#!/usr/bin/env bash
# PostToolUse (Bash): npm test が成功したら dirty marker を消す（内部状態）
set -euo pipefail
. "$(dirname "$0")/_lib.sh"
input=$(cat)
cmd=$(jq -r '.tool_input.command // ""' <<<"$input")
out=$(jq -r '.tool_response.stdout // ""' <<<"$input")
if [[ "$cmd" == *"npm test"* ]] && [[ "$out" == *"fail 0"* ]]; then
  rm -f "$(marker_dir)/$(session_of "$input").src-dirty"
fi
exit 0
EOF
cat > .claude/hooks/stop-test-reminder.sh <<'EOF'
#!/usr/bin/env bash
# Stop: src/ を編集したままテスト未成功で応答を結ぼうとしたら、1 回だけ block して促す（soft）。
# 前回の催促以降に新しい編集が無ければ再催促しない。stop_hook_active で無限ループを避ける。
set -euo pipefail
. "$(dirname "$0")/_lib.sh"
input=$(cat)
[ "$(jq -r '.stop_hook_active // false' <<<"$input")" = "true" ] && exit 0
s=$(session_of "$input")
dirty="$(marker_dir)/$s.src-dirty"; reminded="$(marker_dir)/$s.reminded"
[ -f "$dirty" ] || exit 0
if [ -f "$reminded" ] && [ ! "$dirty" -nt "$reminded" ]; then exit 0; fi
touch "$reminded"
jq -n '{decision: "block", reason: "src/ を編集した後、npm test の成功を確認していません。区切りとして npm test を実行して結果を報告するか、実行を見送る理由をユーザーに明示してから応答を結んでください（docs/design.md）。"}'
exit 0
EOF
cat > .claude/hooks/session-start.sh <<'EOF'
#!/usr/bin/env bash
# SessionStart: 現在ブランチと未完了 plan を注入する（状況提示。stdout が文脈に入る）
set -euo pipefail
cd "${CLAUDE_PROJECT_DIR:-.}"
b=$(git branch --show-current 2>/dev/null || echo "?")
echo "現在ブランチ: $b$([ "$b" = main ] && echo '（main では commit 禁止。/plan-task で分岐）')"
ls dev/tasks/*.md 2>/dev/null | sed 's/^/未完了の plan: /' || true
EOF
chmod +x .claude/hooks/*.sh

# ---- rules / skills / agents / workflows ----
cat > .claude/rules/api.md <<'EOF'
---
paths:
  - "src/api/**/*.js"
---
# API 層の規約（真実源: docs/design.md）
- ハンドラは入力検証を最初に行い、失敗は 400 で返す。
- 例外は握りつぶさず、共通のエラー形式に変換する。
EOF
cat > .claude/skills/quality-gate/SKILL.md <<'EOF'
---
name: quality-gate
description: 区切りごとの品質ゲート。テスト・ビルド・差分の自己レビューを決まった順に行い、結果を成功 / 失敗で報告する。「区切り」「PR 前」と言われたら使う。
disable-model-invocation: false
allowed-tools: Bash(npm test) Bash(npm run build) Bash(git diff *) Bash(git status *)
---
# 品質ゲート (quality-gate)

真実源: docs/design.md「作業の原則」。規約の本文はここに複製しない。

## 手順
1. `npm test` を実行する。失敗したら原因を直す。**テストの削除や skip で通さない**。
2. `npm run build` で dist/ を再生成し、`git status` で dist/ 以外に想定外の変更が無いか見る。
3. `git diff` を読み、設計書に無い変更が混ざっていないか確認する。あれば **ユーザーに確認する**（勝手に進めない）。
4. 結果を「成功 / 失敗」で明言する。失敗時は段名・対象ファイル・エラー文を添える。

## やらないこと
- main への commit / push（hook が止めるが、そもそも試みない）。
- dist/ の手編集。
EOF
cat > .claude/skills/plan-task/SKILL.md <<'EOF'
---
name: plan-task
description: 作業を始めるときの定型手順。feature ブランチを切り、dev/tasks/ に plan ファイルを作って先に commit する。作業に着手する前に必ず使う。
disable-model-invocation: true
---
# 作業開始 (plan-task)

真実源: docs/design.md「作業の原則」。plan ファイルは作業の唯一の真実源で、会話が失われても plan だけで再開できる情報量を持たせる。

## 手順
1. `git switch -c feature/<name> main`
2. `dev/tasks/YYYY-MM-DD-<name>.md` を作る（目的、やること、やらないこと、TODO）。
3. 実装より先に plan だけを commit する。
4. 作業中は TODO を更新するたびに commit する。
EOF
cat > .claude/agents/reviewer.md <<'EOF'
---
name: reviewer
description: 差分を読んで正確性と設計書との整合だけをレビューする。書き換えはしない。レビューを頼まれたら使う。
tools: Read, Grep, Glob
model: sonnet
maxTurns: 15
---
あなたはレビュアーです。指定されたファイルを読み、docs/design.md の原則と照らして、
問題を「file:line、何が問題か、どう直すか」の 3 点で列挙してください。
ファイルの書き換えやコマンドの実行は行わず、指摘だけを返します。指摘が無ければ「指摘なし」と書きます。
EOF
cat > .claude/workflows/review-changes.js <<'EOF'
export const meta = {
  name: 'review-changes',
  description: '変更ファイルをレビューし、指摘を別のエージェントに検証させる',
  phases: [{ title: 'Review' }, { title: 'Verify' }],
}
const changed = await agent('git diff --name-only main を実行し、変更ファイルの一覧を返す。', {
  schema: { type: 'object', required: ['files'], properties: { files: { type: 'array', items: { type: 'string' } } } },
})
const results = await pipeline(
  changed.files,
  f => agent(`${f} を docs/design.md の原則と照らしてレビューし、指摘を列挙する。`, { label: `review:${f}`, phase: 'Review' }),
  review => agent(`次の指摘が本当に問題か、反証を探して検証する: ${review}`, { label: 'verify', phase: 'Verify' }),
)
return results.filter(Boolean)
EOF
cat > scripts/nightly.sh <<'EOF'
#!/usr/bin/env bash
# 夜間に無人で回す例。--bare はホストの hook や CLAUDE.md を読まない（環境差が消える）が、
# プロジェクトの hook も読まないので --settings で明示して渡す。-p の既定は手動なので auto を指定し、
# 人間が答えられないプロンプトは拒否として扱う。結果は JSON で受けて機械で読む。
set -euo pipefail
export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:?set in CI secrets}"
result=$(claude --bare -p "依存関係を更新して npm test を通す。通らなければ何も変更せず理由を報告する" \
  --settings .claude/settings.json \
  --permission-mode auto --permission-prompts none \
  --allowedTools "Bash(npm *),Read,Edit" \
  --output-format json)
echo "$result" | jq -r '.result'
echo "$result" | jq -r '"cost: \(.total_cost_usd) USD"'
EOF
chmod +x scripts/nightly.sh
cat > dev/tasks/2026-09-11-greet-locale.md <<'EOF'
# greet にロケール対応を足す

作業ブランチ: feature/greet-locale / 起点: main
## 目的
挨拶を言語ごとに切り替えられるようにする。
## やらないこと
- 既存の greet(name) の戻り値を変えない。
## TODO
- [x] plan を commit
- [ ] src/greet.js に locale 引数を追加
- [ ] test を追加して npm test
EOF
git add -A >/dev/null && git -c user.name=demo -c user.email=demo@example.com commit -q -m "initial"
if [ "${1:-}" = dirty ]; then
  mkdir -p "${TMPDIR:-/tmp}/claude-hooks-demo-$(id -u)"; touch "${TMPDIR:-/tmp}/claude-hooks-demo-$(id -u)/demo.src-dirty"
fi
